name: Connect to an AWS role from a GitHub repository

on:
  push:
    tags: '*'

env:  
  AWS_REGION : us-east-1

permissions:
      id-token: write
      contents: read
jobs:
  PushDockerImageToECR:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::851725587887:role/GithubActions-Taller3
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      # Se podria hacer algo para pushear con algun tag, 
      # pero por temas de memoria en ECR pusheamos siempre con el tag latest.
      - name: Build, tag, and push the image to Amazon ECR Public
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: q1r8t3l6
          REPOSITORY: tinder-gateway
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
